name: space_shooter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  getwidget: ^3.0.1
  flame: ^1.6.0

dev_dependencies: 
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter_icons:
  android: "icon_launcher"
  ios: true
  image_path: "assets/images/player.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true # remove alpha channel from ios icons
  web:
    generate: true
    image_path: "assets/images/player.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/player.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/player.png"


flutter: 
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/audio/